[package]
name = "concat-kdf"
version = "0.1.0"
description = "Concatenation Key Derivation Function (Concat KDF)"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/concat-kdf"
repository = "https://github.com/RustCrypto/KDFs"
keywords = ["crypto", "concat-kdf", "KDF", "NIST"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.10.7"

[dev-dependencies]
hex-literal = "0.3.4"
sha2 = { version = "0.10.3", default-features = false }

[features]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
